async function fetchAllSymbols() {
  allSymbols = [
    'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT',
    'ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT',
    'MATICUSDT','LTCUSDT','UNIUSDT','ATOMUSDT','NEARUSDT',
    'FTMUSDT','ALGOUSDT','VETUSDT','ICPUSDT','FILUSDT',
    'SANDUSDT','MANAUSDT','AXSUSDT','GALAUSDT','APEUSDT',
    'OPUSDT','ARBUSDT','INJUSDT','SUIUSDT','SEIUSDT',
    'TIAUSDT','WLDUSDT','FETUSDT','AGIXUSDT','RENDERUSDT',
    'LDOUSDT','STXUSDT','RUNEUSDT','AAVEUSDT','CRVUSDT',
    'MKRUSDT','COMPUSDT','SNXUSDT','DYDXUSDT','GMXUSDT',
    'TRXUSDT','EOSUSDT','ETCUSDT','BCHUSDT','XMRUSDT',
    'HBARUSDT','ZILUSDT','ONTUSDT','QTUMUSDT','OCEANUSDT',
    'ANKRUSDT','SKLUSDT','AUDIOUSDT','FLOWUSDT','ROSEUSDT',
    'IMXUSDT','LRCUSDT','MASKUSDT','ENSUSDT','JASMYUSDT',
    'RVNUSDT','BALUSDT','BANDUSDT','KNCUSDT','STORJUSDT',
    'SPELLUSDT','PERPUSDT','CFXUSDT','WOOUSDT','ICXUSDT',
    'KAVAUSDT','IOTAUSDT','CELOUSDT','ALPHAUSDT','COTIUSDT',
    'REQUSDT','OGNUSDT','KLAYUSDT','MINAUSDT','RNDRUSDT',
    'LOOKSUSDT','BLURUSDT','STGUSDT','MAGICUSDT','HIGHUSDT',
    'TUSDT','GALUSDT','IDUSDT','EDUUSDT','MNTUSDT',
    'CYBERUSDT','ARKUSDT','FRONTUSDT','POWRUSDT','COMBOUSDT',
    'WAXPUSDT','RIFUSDT','POLYXUSDT','GASUSDT','VIBUSDT'
  ];
  console.log('Binance TR parite sayisi: ' + allSymbols.length);
}